### ISSUE TITLE
Change order of grouping categories in Venn diagram

### ISSUE THREAD

**Issue by camillethuyentruong** [Russel88/MicEco#10]
Hey,

Thanks for the fantastic package! Is there a way to change the order of grouping categories when plotting Venn diagrams with function `ps_venn`?

In the example below, I would like the category PUM.ANT between PUM and ANT, and PUM.BET between PUM and BET.

![Rplot01](https://user-images.githubusercontent.com/46766469/139718605-498ed7b3-1140-48f3-a0bf-038a91a41e4f.png)

Cheers
Camille

**Comment by Russel88** [comment]
Hi Camille,

You can change the order of levels for the factor, and the ordering in the venn diagram should follow:
`sample_data(ps)$Var<- factor(sample_data(ps)$Var, levels = c("ANT", "PUM.ANT", "PUM", "PUM.BET", "BET"))`
`ps_venn(ps, "Var")`

Cheers,
Jakob

**Comment by camillethuyentruong** [comment]
That works well. Thanks!
