### ISSUE TITLE
Plot  ASV counts and relative abundance

### ISSUE THREAD

**Issue by SimonMorvan** [Russel88/MicEco#11]
Hello,

Thank you for this useful package! 
Would there be a way to combine both the ASV/OTU count and the relative abundance they represent using weight = T in the plotted Venn diagram ? 

Have a great day,

Simon

**Comment by Russel88** [comment]
Hi Simon,

Do you mean such that there are labels with both the count and the overlap in relative abundance, e.g. 230 (20%), where 230 is the actual count in that set, and 20% is the relative-abundance-weighted count?

Cheers

**Comment by SimonMorvan** [comment]
Hi Jakob,
Yes, exactly! 
I find both numbers useful but I was unable to plot both on the same figure. 
Cheers, 
Simon

**Comment by Russel88** [comment]
Hi Simon,
Unfortunately, that's not possible. You would have to make two figures and move the labels from one to the other.
Cheers,
Jakob

**Comment by Russel88** [comment]
But you can manually input the labels you want to plot:
`ps_venn(phy, "Var", quantities = list(labels = c("Test1","Test2","Test3","Test4","Test5","Test6","Test7")))`

**Comment by SimonMorvan** [comment]
Alright, thank you, I'll try that !
