### ISSUE TITLE
ps_venn and ps_euler give different results

### ISSUE THREAD

**Issue by camillethuyentruong** [Russel88/MicEco#12]
Hi Russel, I have been playing with your package and really enjoy it!

Based on the same dataset, the Venn and Euler diagrams look different and I don't understand why. For example in the Euler plot, what happened to the 23 OTUs shared between all forest types in the Venn plot? Am I missing something here?

Thanks!

```
ps_venn(
  data,
  group = "ForestType",
  quantities = list(type=c("counts")),
  plot = TRUE
  )
```
![image](https://user-images.githubusercontent.com/46766469/145829868-e51e979f-e8d3-4725-8795-283aa0ceaa12.png)

```
ps_euler(
  data,
  group = "ForestType",
  quantities = list(type=c("counts")),
  plot = TRUE
  )
```
![image](https://user-images.githubusercontent.com/46766469/145829993-0d1a560c-e19d-4ace-87be-4f1920cbaec4.png)

**Comment by Russel88** [comment]
Dear Camille,

Optimal euler plots are often not theoretically possible to make with more than 3 groups, so the function will just plot the best fitting one, which can exclude some non-zero overlaps.

In the next version of MicEco I will add a message warning the user if some taxa are excluded in the plot.

Best, Jakob

**Comment by camillethuyentruong** [comment]
Thanks Jacob, do you now based on which criteria are those overlaps eliminated? Is there a way to keep them even though the figure looks ugly?

**Comment by Russel88** [comment]
As far as I know it's not possible. The function uses the R package eulerr, and you can see how it works here: https://cran.r-project.org/web/packages/eulerr/vignettes/under-the-hood.html

It is possible to make quasi-proportional Venn diagrams with nVennR, however I think they can be hard to read: https://cran.r-project.org/web/packages/nVennR/vignettes/nVennR.html

**Comment by camillethuyentruong** [comment]
Ok thanks, maybe I'll stick with Venn diagrams then, as the Euler plot gives the false impression that no OTUs are shared between all forest types.

**Comment by Russel88** [comment]
If you update to the newest MicEco version you can now use the `shape="ellipse"` argument, which might make it possible to make a plot with all overlaps
