### ISSUE TITLE
ps_venn some advice (percent and label)?

### ISSUE THREAD

**Issue by marwa38** [Russel88/MicEco#13]
It was easy to use ps_venn
I was wondering if it is possible to change the labels of the circles to be on their edges?
so rather than 
![image](https://user-images.githubusercontent.com/68851733/147290242-dbe48cc4-5653-406b-a24c-fb6fd409a1a2.png)

is to be like 
![image](https://user-images.githubusercontent.com/68851733/147290209-985365c9-7162-4ea5-b612-91eb7255aba4.png)

So also can I make changes where the percents appear only on the cross-section between circles and not for every circle?
to only have % in here as you can see (screenshot from my first fig shared)
![image](https://user-images.githubusercontent.com/68851733/147290334-05c8493b-5904-4454-ae31-14d2af6bda9a.png)

here are my codes 
```
ps_venn(ps.prev, 
        group = "treatment", 
        quantities = list(type=c("percent","counts"), font = 2),
        labels = list(cex = 1)
```

**Comment by Russel88** [comment]
Dear marwa38,

As far as I know, these things are not possible with the eulerr package (which ps_venn is wrapping). 
My suggestion would be to save the plots as vector graphics and make these changes in inkscape or similar.

Best,
