### ISSUE TITLE
fraction setting and OTUs in venn plot

### ISSUE THREAD

**Issue by hassantarabai** [Russel88/MicEco#15]
Hello,

Thank you for the great tool. I am preparing some ven diagrams based on different fractions(0.3,0.5 and 0.7). I expected to see OTUs that are persent in fraction 0.7, are also present in lower fraction settings(0.3 and 0.5) but that is not always the case.

Am i missing something ?

Thank you,

**Comment by Russel88** [comment]
Hi

Yes, OTUs in lower fractions should be present in higher fractions. Can you share an example dataset with this problem, so I can investigate the problem?

Regards,
Jakob

**Comment by hassantarabai** [comment]
Hi,

Thank you, here is one subset where the problem is appearing. I also atttached the lists of OTUs using different fraction settings.
I am using the following settings to obtain the OTU lists:

venn<-ps_venn(N18,"Sample_type", plot = FALSE ,WEIGHT = TRUE, relative = TRUE, fraction = 0.5, quantities = list(type=c("percent","counts"), font = 2), labels = list(cex = 2), col = "black", fill = c("red","blue","grey"))

[N18_subset_vin_results.zip](https://github.com/Russel88/MicEco/files/8418323/N18_subset_vin_results.zip)

**Comment by Russel88** [comment]
I think what is happening is correct.
If we for example look at OTU_24 in your example:
With fraction 0.3 it's in "assassin__Tick__Triatoma", with 0.5 it's in "Tick__Triatoma", and with 0.7 it's in "Triatoma".
So it is only present in at least 70% of the samples in the Triatoma group, it's present in at least 50% of the samples in the Tick group, and it's present in at least 30% of the samples in all three groups.

Does this resolve your confusion, or is it another problem you are referring to?

**Comment by hassantarabai** [comment]
Hello,

Yah great, thank you for the fast feedback.

Regards,
