### ISSUE TITLE
Supported groups

### ISSUE THREAD

**Issue by alanxelena** [Russel88/MicEco#16]
Hi Russel!

   I am using ps_venn which I find super useful, my only question is, I am trying to run a diagram for 10 variables but I get an error stating that the max groups admitted are 5. Is there a workaround this? I understand the final plot would look really messy but I would like to see how it turns out.
   
 Thanks!!

**Comment by Russel88** [comment]
Hi

The package used to draw Venn diagrams cannot draw them with more than 5 groups. However, you can try ps_euler which makes Euler diagrams. There is no group limit with Euler diagrams, but it might be a big mess with 10 groups.

Cheers,
Jakob

**Comment by alanxelena** [comment]
Thank you very much for your reply!
