### ISSUE TITLE
Can we display percentages for each group rather than across all groups ps_euler 

### ISSUE THREAD

**Issue by ZLouisson** [Russel88/MicEco#17]
Hi, I'm finding the ps_euler command really useful, however I was wondering if there is a way to display the quantities as percentages of each group, rather than across all the groups. I would like to see what proportion of each group is unique vs shared.

Thanks!

**Comment by Russel88** [comment]
Hi. I'm pretty sure that is not possible. That would print 2 percentage values when 2 groups are overlapping, 3 values when 3 groups are overlapping, and so on. I think you have to do add it manually to the plot
