### ISSUE TITLE
Number of reads to sample when using rarefy_rrna

### ISSUE THREAD

**Issue by eperezv** [Russel88/MicEco#18]
Hello,

First of all, thank you for coding this package, which I use a lot to speed up ses.mpd calculations on a multi-core machine.

I have a question regarding the number of reads to sample when using rarefy_rrna. I think that choosing the number of reads is not that straightforward as when using any other simpler rarefaction tool. I think choosing something like min(sample_sums(physeq)) as the number of reads is not completely correct as we are correcting and estimating the number of reads based on the fact that some organisms have multiple copies of the rRNA operon.

Do you have any suggestion or recommendation on how to choose the number?

Thank you,
Eduardo

**Comment by Russel88** [comment]
Hi Eduardo,

rarefy_rrna is very much experimental, so I don't have a clear answer for you. 
But for choosing the depth, you have to be aware that rarefaction is based on the rrarefy function from vegan which is without replacement. This means that if the rarefaction depth is close to the actual read depth, the rRNA copy numbers will have very little impact on the resulting rarefied community matrix. Basically, you can never get more reads of certain taxa in the rarefied matrix. So if you want the rRNA copy number to have an effect the rarefied depth has to be significantly lower than the actual depth, and has to be that for all samples to be unbiased. Alternatively, one could add replacement when sampling reads, which should give a bigger impact of copy numbers.

It is of course problematic to choose a low rarefaction depth, as you will loose sensitivity for downstream analyses.

Best,
Jakob

**Comment by Russel88** [comment]
I have added an option to sample with replacement in the new version of MicEco 0.9.18
