### ISSUE TITLE
Using community_rrna with Silva reference database for taxonomy

### ISSUE THREAD

**Issue by bippuspm** [Russel88/MicEco#19]
Hi,

I'm trying to use the community_rrna function but I have trained my taxa from the Silva database because Greengenes hasn't been updated. The function says I can use an OTU-table with taxa as rows and OTU names as rownames and a dataframe with two variables: "ID" is the OTU id matched by rownames in x and "Copy" is the copy number. However, that doesn't include any sample information. Shouldn't the OTU table have OTUs as rownames and samples as column names and the frequency of each OTU in each sample? 

If this doesn't work, can you post the fasta file you used from Greengenes to assign taxonomy in your phyloseq?

Thanks!

**Comment by Russel88** [comment]
Hi,

Yes, the OTU-table should have samples as columns and the frequency of them. This function was written back when Greengenes wasn't so outdated. I would suggest that you align your OTUs against the rrnDB database. This way you can obtain a data.frame with the estimated copy number for each OTU: https://rrndb.umms.med.umich.edu/

Cheers,
Jakob

**Comment by bippuspm** [comment]
Jakob,

That's exactly what I did--thank you! My only concern is I got a warning that said "the condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be used".

Does this warning mean it wasn't able to be weighted by abundances?

Thanks,
Paige


--

Paige Varner

PhD Candidate

Civil and Environmental Engineering I Duke University

Contact: ***@***.*** | she/her

________________________________

**Comment by Russel88** [comment]
Hi Paige,

Could you send the code you used and the full error message. It's hard to say what has gone wrong from what you write.

**Comment by Russel88** [comment]
Closing due to no answer
