### ISSUE TITLE
Error in rep(rrna.rev, times = x[i, ]) : invalid 'times' argument

### ISSUE THREAD

**Issue by mars91-sc** [Russel88/MicEco#2]
Hi, this is my command and output:

rarefy_rrna.matrix(EQM_spec_Z1_TaxID_sorted_by_Abundance_descending, 1000, copy.database = "v13.5", seed = NULL,
+             trim = FALSE)
Remember to set seed! Now set to 1562117525.63036
Error in rep(rrna.rev, times = x[i, ]) : invalid 'times' argument

I'm not sure about the usage of 'times' here.

**Comment by Russel88** [comment]
Hi,

Does it work if you run the vegan function rarefy on the matrix?
If this works, can you send me a sample dataset, such that I can reproduce and fix the error?

Cheers,

**Comment by Russel88** [comment]
No respond
