### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by wwwweber** [Russel88/MicEco#24]
Hello!

I'm using two dfferent functions (ps_venn and plot(venn(list_core)) and I'm obtaining two different results. I'm not understanding why this is happening, as the dataset is the same for both diagrams. I think there's something with the parameters..

![diagrama de Venn 1](https://user-images.githubusercontent.com/103456637/232857274-b9b835c1-61e3-456b-8bb4-462baf5cd772.png)
![venn2](https://user-images.githubusercontent.com/103456637/232857306-96411128-0014-4021-829b-81ed56cf73b4.png)

For the Diagram 1, using eulerr, microbiome and microbiomeutilities packages, the script is:

for (n in situation_list)
  
  ps.sub <- subset_samples(ps.rel, Situation == n) 
  
  core_m <- core_members(ps.sub, 
                         detection = 0.001, 
                         prevalence = 0.50)
  print(paste0(n, length(core_m))) 
  list_core[[n]] <- core_m 

}

mycols <- c(Wild, Captive) 
venn <- plot(venn(list_core),
     fills = mycols)

venn

For the Diagram 2, using MicEco package, the script is:
venn2 <- ps_venn(ps3_dna, 
                "Situation", 
                fraction = 0.5, 
                weight = FALSE, 
                relative = TRUE, 
                plot = TRUE, #
)

venn2

Could you, please, help me understand that? Do you have any instructions on how to perform this analysis properly?

Thanks in advance!

**Comment by Russel88** [comment]
In the first Venn diagram, it looks like you are using a detection threshold. I am not familiar with that function, but that would certainly make a difference. In the MicEco function there is no detection threshold, everything is counted. You could use ps_prune to remove low abundant and run the resulting phyloseq through ps_venn. Then I guess the diagrams should be similar

**Comment by Russel88** [comment]
No answer
