### ISSUE TITLE
Error in do.call(c, singles[-x]) : second argument must be a list

### ISSUE THREAD

**Issue by wwwweber** [Russel88/MicEco#25]
Hello!

I am having this error message (Error in do.call(c, singles[-x]) : second argument must be a list) when trying to print the list using ps_venn. Here follows the code:

venn_list <- ps_venn(ps3_dna.t,
                      "Situation",
                      fraction = 0.9, 
                      weight = FALSE,
                      relative = TRUE, 
                      plot = FALSE, 
)

venn_list

I am using an agglomerated (genus level) phyloseq object.

Any advice on that? 

Thanks in advance!

**Comment by Russel88** [comment]
Hi

Does it work when you try to plot it, do you get a sensible plot?
When I look at the code it looks like it could fail if all features are found in at least 2 groups, could that be the case with your data?

**Comment by Russel88** [comment]
No answer
