### ISSUE TITLE
In ps_venn percentage does not add up to 100%

### ISSUE THREAD

**Issue by zohrazahir** [Russel88/MicEco#26]
Hi MicEco :)

I am using ps_venn function, but the percentage of each group does not add up to 100%. I used this code before taking the number of samples into account: 

```
ps_venn(
  ps.prop,
  group = "Ecosites", type = "Pond"
)
```
And this is the diagram: 

![Venn_no_fraction](https://github.com/Russel88/MicEco/assets/72106136/615bb553-2d41-4739-a5d5-85d8a0ebf085)

And then I added the fraction: 

fractions <- c(Dugout = 0.2, Upland = 0.2, Lowland = 0.6)

ps_venn(
  ps.prop,
  group = "Ecosites", type = "Pond", relative = TRUE, quantities = list(type = c("percent", "counts")), fraction = fractions
)

And got this: 

![Venn_with_fraction](https://github.com/Russel88/MicEco/assets/72106136/9ac09dad-8c37-478e-baed-a8ae709bd738)

But the sum of the unique and common percentages does not add up. Any idea what went wrong? 

Thank you,
Z.

**Comment by Russel88** [comment]
I'm not sure what you mean. 
In the last plot the percentages all add up to 100%

**Comment by zohrazahir** [comment]
Hi @Russel88,

Ah! Did you sum up all ecosites to get 100? That makes sense; I was summing each ecosites individually. Do you know what "counts" indicate, then?

**Comment by Russel88** [comment]
Yes, it's a percentage across all. The counts are the actual number of ASVs/OTUs or whatever feature you have in your input

**Comment by zohrazahir** [comment]
Thank you so much Russel for the clarification. 

Cheers,
z.
