### ISSUE TITLE
Area-proportional Venn diagram?

### ISSUE THREAD

**Issue by marwa38** [Russel88/MicEco#27]
Hi team 
Thanks for making things easier to create a Venn diagram directly on phyloseq object. 
Area-proportional Venn diagram (also called a Venn diagram by area) is preferable because of grasping the idea of shared and unique quickly. 
This is a suggestion to implement to your wonderful package, if possible?  
Cheers
M

**Comment by Russel88** [comment]
Hi
I have included Euler diagrams, which are area-proportional. Is this not what you are proposing?

**Comment by marwa38** [comment]
Thanks so much, @Russel88  name of the function please, or argument in the function?/quick example if you applied yourself? Thanks for applying this feature, will try and come back to you.

**Comment by Russel88** [comment]
It's the ps_euler function, which takes the same arguments as the ps_venn function
