### ISSUE TITLE
ps_venn

### ISSUE THREAD

**Issue by bholt20** [Russel88/MicEco#3]
Trying to produce a venn of ASV overlap between two samples. I have my phyloseq object with my sample_data(ps). Im trying to group by a categorical variable in my sample data (either spec or environ) and keep getting this error:

ps_venn(stdc2, group = 'Type', type = 'counts')
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate

after checking my phlyloseq object, it looks normal:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 87079 taxa and 62 samples ]
sample_data() Sample Data:       [ 62 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 87079 taxa by 7 taxonomic ranks ]

Note: my sample_names(ps) are only numbers. Is this error because my sample names are not the grouping variable?

**Comment by Russel88** [comment]
I can't seem to reproduce your error, with my own datasets. 
Could you provide a small dataset on which I can reproduce the error?

**Comment by bholt20** [comment]
[ps_venn.RDS.zip](https://github.com/Russel88/MicEco/files/4450441/ps_venn.RDS.zip)

**Comment by Russel88** [comment]
Hi Ben,
This was a bug, which is now [fixed.](https://github.com/russel88/MicEco/commit/9ec6c3002c808f7ff880ca8bdb45db16d4fd9b89) If you install MicEco again it should work.
I'm closing this issue, but you are welcome to re-open it if the problem persists
Cheers,
Jakob

**Comment by bholt20** [comment]
Hey Jakob,

Yes, everything working as it should now. Thanks for the quick response and help!

Ben
