### ISSUE TITLE
request to add in export list of unique OTUs and shared OTU

### ISSUE THREAD

**Issue by Joyce2896** [Russel88/MicEco#7]
Hi Russel88, 
I like your venn diagram display. However, I find it difficult to extract the unique taxa and shared taxa through the console, when I set the plot to "False". Hence, I would love to see an add-on features to export the list, or into a data frame. Thank you

**Comment by Russel88** [comment]
Hi. If you prefer a dataframe to a list, running stack() on the output should convert it accordingly.
Cheers,
Jakob

**Comment by Joyce2896** [comment]
I tried running on stack. But the result display still on the console like a print screen function (as below). I'm wondering is there a way I can export the list out? 

`stack(ps_venn(mybac3Br, group ="Treatment", type = "counts", plot = "FALSE"))`
       values
1     OTU_816
2    OTU_1485
3    OTU_1527
4    OTU_1656
5    OTU_1672
6    OTU_1850
7    OTU_2017
8    OTU_2215
9    OTU_2253
10   OTU_2381
11   OTU_2430
12   OTU_2697
13   OTU_2836
14   OTU_2959
15   OTU_3021
16   OTU_3080
17   OTU_3101
18   OTU_3109
19   OTU_3157
20   OTU_3193
21   OTU_3213
22   OTU_3228
23   OTU_3278
24   OTU_3304
25   OTU_3311
26   OTU_3390
27   OTU_3414
28   OTU_3421
29   OTU_3430
30   OTU_3513
31   OTU_3532
32   OTU_3588
33   OTU_3613
34   OTU_3642
35   OTU_3649
36   OTU_3669
37   OTU_3671
38   OTU_3701
39   OTU_3709
40   OTU_3740
41   OTU_3792
42   OTU_3813
43   OTU_3814
44   OTU_3834
45   OTU_3835
46   OTU_3837
47   OTU_3849
48   OTU_3859
49   OTU_3867
50   OTU_3879
51   OTU_3946
52   OTU_3963
53   OTU_3975
54   OTU_3982
55   OTU_4017
56   OTU_4034
57   OTU_4063
58   OTU_4077
59   OTU_4127
60   OTU_4134
61   OTU_4154
62   OTU_4155
63   OTU_4157
64   OTU_4170
65   OTU_4199
66   OTU_4217
67   OTU_4220
68   OTU_4231
69   OTU_4251
70   OTU_4262
71   OTU_4279
72   OTU_4289
73   OTU_4315
74   OTU_4326
75   OTU_4396
76   OTU_4421
77   OTU_4436
78   OTU_4448
79   OTU_4470
80   OTU_4481
81   OTU_4483
82   OTU_4500
83   OTU_4515
84   OTU_4520
85   OTU_4535
86   OTU_4565
87   OTU_4566
88   OTU_4568
89   OTU_4595
90   OTU_4610
91   OTU_4644
92   OTU_4652

 [ reached getOption("max.print") -- omitted 5324 rows ]

**Comment by Russel88** [comment]
You could try the following then:

mylist <- ps_venn(...) 
capture.output(summary(mylist), file = "venn.txt")

**Comment by Joyce2896** [comment]
Yes, now it works! Thank you so much Russel88 👍

**Comment by Russel88** [comment]
You're welcome

**Comment by Russel88** [comment]
Hi

I'm writing to you since I unfortunately discovered a bug in the ps_venn function in MicEco. When running with plot=FALSE some taxa can be falsely omitted in the output if your group factor has more than 3 levels. 
It is now fixed in the new version (0.9.15). I apologize for this.

Kind regards,
Jakob

**Comment by Joyce2896** [comment]
Dear Jakob,

Thank you for letting me know on this. I did noticed on the bug, appreciate very much that you had fix it. ☺

Thank you.
Regards,
Joyce
