### ISSUE TITLE
Citation 

### ISSUE THREAD

**Issue by Hesham999666** [Russel88/MicEco#8]
Hi Russel 

How do I  cite my MicEco package in my paper ?

Hesham

**Comment by Russel88** [comment]
Hi Hesham

I have not published a paper on this package, but you can cite it through the stable doi at Zenodo:
https://doi.org/10.5281/zenodo.4639787

For example as:
Jakob Russel. (2021). Russel88/MicEco (Version v0.9.14). Zenodo. http://doi.org/10.5281/zenodo.4639787

Thank you for asking,
Jakob
