### ISSUE TITLE
Font size in ps_venn

### ISSUE THREAD

**Issue by George-Crane** [Russel88/MicEco#9]
Hey,

Thanks for the fantastic package, and function ps_venn. 

I have been unable to change the font size of the numbers and/or labels. Could you please help?

Best wishes.

**Comment by Russel88** [comment]
Hi George

I'm glad you find the package useful!

Additional arguments to the ps_venn function are passed to the plot.venn function, so anything that works for that should work. 
See more here: https://cran.r-project.org/web/packages/eulerr/vignettes/gallery.html
Hint: cex is controlling font size

Cheers, 
Jakob

**Comment by George-Crane** [comment]
Hey Jakob,

Thanks for the speedy reply! This is as I thought, although the issue is still persisting for the values which I had been ’testing’ the code on..

I am now able to change the size of the labels, legend and title, but not the values (quantities/counts). It returns the error:

"Error in plot.venn(df, quantities = list(type = type), ...) : 
  formal argument "quantities" matched by multiple actual arguments”

My code is:

ps_venn(df, "Treatment",
        labels=list(cex=1.5),
        legend=list(cex=1.5),
        main=list(cex=2, labels='Site Name'),
        fraction = 0, 
        type = "counts",
        quantities = list(cex=1.5),
        fill =c("Trt1" ="#E69F00",
                "Trt2" ="#56B4E9",
                "Trt2" ="#009E73”))

Any ideas greatly received. 

Best wishes,
George

**Comment by Russel88** [comment]
Aha. ps_venn overwrites the quantities argument, so changing the font of the quantities is not supported, but I can make a small change to fix it

**Comment by Russel88** [comment]
Fixed now. You're welcome to reopen this issue if it doesn't work
